import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  teams,
  analytics,
}: {
  children?: React.ReactNode;
  teams: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mb-6 p-4 bg-blue-500 text-white text-lg">
          Root Layout
        </div>
        <div className="gap-5 flex justify-center align-middle">
          <div>{teams}</div>
          <div>{analytics}</div>
        </div>
      </body>
    </html>
  );
}
