import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import Products from "@/app/components/Products";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>Root Layout For Admin Route Group</div>
      {children}
      <ErrorBoundary fallback={<Error />}>
        <Products />
      </ErrorBoundary>
    </>
  );
}
