import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Loading from "./loading";
import { Suspense } from "react";
import dynamic from "next/dynamic";

const Products = dynamic(() => import("../components/Products"), {
  suspense: true,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>Root Layout</div>
        <Suspense fallback={<Loading />}>
          <Products />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
